from __future__ import annotations

from datetime import datetime


def _entry(
    idx: int,
    screen_key: str,
    title: str,
    description: str,
    when_to_use: str,
    steps: list[str],
    rules: list[str],
    errors: list[str],
    tips: list[str],
    module: str,
    submodule: str,
    route_path: str,
):
    return {
        "id": idx,
        "screen_key": screen_key,
        "title": title,
        "description": description,
        "when_to_use": when_to_use,
        "steps_json": steps,
        "rules_json": rules,
        "errors_json": errors,
        "tips_json": tips,
        "module_name": module,
        "submodule_name": submodule,
        "route_path": route_path,
        "is_active": True,
        "created_at": datetime.utcnow(),
    }


HELP_CONTENT_SEED = [
    _entry(1, "dashboard_main", "Dashboard", "Execution control center with widgets and pending actions.", "Immediately after login to review day priorities.", ["Review widgets", "Open pending approvals", "Check notifications", "Drill into modules"], ["RBAC controls widget visibility", "Data scope limits records"], ["Widget missing due to permission"], ["Keep only useful widgets"], "Dashboard", "Main", "/dashboard"),
    _entry(2, "dashboard_widget_settings", "Widget Settings", "Configure dashboard widget layout.", "When adding/removing/reordering widgets.", ["Open settings", "Toggle widgets", "Save layout"], ["Admin may lock widgets"], [], ["Keep critical widgets on top"], "Dashboard", "Settings", "/dashboard/settings"),
    _entry(3, "dashboard_create_widget", "Create Widget", "Build custom KPI/chart/table widgets.", "When prebuilt widgets are insufficient.", ["Select dataset", "Map axes", "Choose chart", "Preview", "Save"], ["Datasets are RBAC filtered"], ["Invalid axis combination"], ["Save reusable views"], "Dashboard", "CreateWidget", "/dashboard/widgets/create"),
    _entry(4, "dashboard_analytics_panel", "Dashboard Analytics", "Trend and comparative analytics for selected data.", "When deeper module insights are needed.", ["Open analytics", "Apply filters", "Review trends", "Export"], ["Global filters apply"], [], ["Use date windows for trend quality"], "Dashboard", "Analytics", "/dashboard/analytics"),
    _entry(5, "project_list", "Project List", "List all projects in your scope.", "To search, filter, and open projects.", ["Filter projects", "Open details", "Use action menu"], ["Visibility is role-based"], [], ["Filter by health + status"], "Project", "List", "/projects"),
    _entry(6, "project_create", "Create Project", "Create new project with team, budget, and phases.", "For onboarding new engagements.", ["Enter project details", "Assign manager + POCs", "Define phases/steps", "Save"], ["Mandatory POCs required", "Client is required"], ["Missing team POC"], ["Define phase structure early"], "Project", "Create", "/projects/create"),
    _entry(7, "project_edit", "Edit Project", "Update project ownership, budget, and structure.", "When project plan changes.", ["Open project", "Edit section", "Save"], ["End date cannot be reduced", "Extension may create rollover"], [], ["Check budget impact before save"], "Project", "Edit", "/projects/:id/edit"),
    _entry(8, "project_detail", "Project Details", "Complete project profile and linked entities.", "Before planning/approval decisions.", ["Open project", "Review tabs", "Navigate to linked tasks/phases"], ["Details depend on permission"], [], ["Use detail view before approval"], "Project", "Detail", "/projects/:id"),
    _entry(9, "project_dashboard", "Project Dashboard", "Progress, cost, effort, health and risk view.", "For execution review.", ["Open dashboard tab", "Review KPIs", "Drill into risks"], ["Health is system calculated"], [], ["Track budget variance weekly"], "Project", "Dashboard", "/projects/:id/dashboard"),
    _entry(10, "project_pocs", "Project POCs", "Manage communication owners for project.", "When contact ownership changes.", ["Add/edit POCs", "Save", "Use contact actions"], ["Mandatory internal groups required"], [], ["Keep contact details current"], "Project", "POC", "/projects/:id/pocs"),
    _entry(11, "project_budget", "Project Budget", "Maintain estimated vs actual budget/hours.", "For profitability control.", ["Enter estimates", "Save", "Monitor variance"], ["Actuals are system-driven"], [], ["Review planned vs actual frequently"], "Project", "Budget", "/projects/:id/budget"),
    _entry(12, "project_phase_list", "Project Phases", "Manage project phases.", "For stage-wise planning.", ["Review phases", "Add/edit phase", "Open linked tasks"], ["Phase belongs to one project"], [], ["Keep phases logically grouped"], "Project", "PhaseList", "/projects/:id/phases"),
    _entry(13, "project_phase_create", "Create Phase", "Add project milestone phase.", "When structuring project work.", ["Enter phase name", "Set dates", "Save"], ["Phase dates align to project range"], [], ["Use business-meaningful names"], "Project", "PhaseCreate", "/projects/:id/phases/create"),
    _entry(14, "project_step_builder", "Step Builder", "Define project steps that convert to tasks.", "During setup or replanning.", ["Add step", "Set owner + hours", "Save"], ["Steps convert to tasks"], [], ["One outcome per step"], "Project", "StepBuilder", "/projects/:id/steps"),
    _entry(15, "task_list", "Task List", "Execution tasks across projects/phases.", "To monitor and open tasks.", ["Filter tasks", "Open task", "Review jobs/dependencies/SLA"], ["Tasks are project-linked"], [], ["Use status + priority filters"], "Task", "List", "/tasks"),
    _entry(16, "task_create", "Create Task", "Create task under project and phase.", "For planned execution work.", ["Select project+phase", "Choose task master", "Set timeline/dependencies", "Assign users", "Save"], ["Task master required", "Dependencies must be valid"], ["Estimation exceeds benchmark"], ["Keep tasks granular"], "Task", "Create", "/tasks/create"),
    _entry(17, "task_edit", "Edit Task", "Modify task plan and assignments.", "When execution changes.", ["Open task", "Edit fields", "Save"], ["Deadline extension may trigger rollover"], [], ["Check downstream impacts"], "Task", "Edit", "/tasks/:id/edit"),
    _entry(18, "task_detail", "Task Details", "Full task context and linked execution.", "Before status/approval action.", ["Open task", "Review tabs", "Take authorized action"], ["Completion may depend on jobs/approvals"], [], ["Check SLA and dependency before status change"], "Task", "Detail", "/tasks/:id"),
    _entry(19, "task_dependency", "Task Dependencies", "Define or inspect predecessor links.", "When sequencing matters.", ["Select parent task", "Save dependency"], ["Dependent task cannot start first"], [], ["Avoid deep unnecessary chains"], "Task", "Dependency", "/tasks/:id/dependencies"),
    _entry(20, "task_jobs_tab", "Task Jobs", "Jobs under selected task.", "For person-wise execution tracking.", ["Open jobs tab", "Review jobs", "Open job detail"], ["One task can contain many jobs"], [], ["Use jobs for execution granularity"], "Task", "JobsTab", "/tasks/:id/jobs"),
    _entry(21, "task_timesheet_tab", "Task Timesheets", "Timesheet effort linked to task.", "For effort and cost review.", ["Open tab", "Review hours", "Compare against plan"], ["Overlap entries are flagged"], [], ["Watch leakage here"], "Task", "TimesheetsTab", "/tasks/:id/timesheets"),
    _entry(22, "task_status_history", "Task Status History", "System-generated status trail.", "For audit and delay analysis.", ["Open history", "Review user/action/time"], ["History is immutable trail"], [], ["Use before root-cause analysis"], "Task", "StatusHistory", "/tasks/:id/status-history"),
    _entry(23, "job_list", "Job List", "Jobs assigned under tasks.", "To manage person-wise execution.", ["Filter jobs", "Open job", "Review SLA/time"], ["Job belongs to one task"], [], ["Review pending jobs daily"], "Job", "List", "/jobs"),
    _entry(24, "job_create", "Create Job", "Create person-assigned execution job.", "When assigning work under task.", ["Select task", "Select employee", "Set timeline", "Save"], ["Dependency may restrict start", "Conflict scheduling may block"], [], ["Check calendar before assign"], "Job", "Create", "/jobs/create"),
    _entry(25, "job_edit", "Edit Job", "Update job owner or timeline.", "When ownership/schedule changes.", ["Open job", "Edit", "Save"], ["Extensions create rollover"], [], ["Review timesheet history before reassignment"], "Job", "Edit", "/jobs/:id/edit"),
    _entry(26, "job_detail", "Job Details", "Complete job execution record.", "For operational/approval review.", ["Open job", "Review linkage and SLA"], ["Closure may depend on timesheet/approval"], [], ["Check cost/time before closure"], "Job", "Detail", "/jobs/:id"),
    _entry(27, "job_timesheet_view", "Job Timesheets", "Timesheets linked to job.", "For effort and reimbursement review.", ["Open job timesheets", "Review entries"], ["Time logged affects cost"], [], ["Compare actual vs planned often"], "Job", "Timesheets", "/jobs/:id/timesheets"),
    _entry(28, "job_cost_analysis", "Job Cost Analysis", "Costing and billing alignment by job.", "For overrun detection.", ["Open cost analysis", "Compare hours/cost/billing"], ["Actual cost is system-driven"], [], ["Catch overruns early"], "Job", "Cost", "/jobs/:id/cost"),
    _entry(29, "timesheet_list", "Timesheet List", "All timesheet entries in scope.", "For review and overlap checks.", ["Filter entries", "Open entry", "Review impact"], ["Entries tied to jobs"], [], ["Monitor overlaps daily"], "Timesheet", "List", "/timesheets"),
    _entry(30, "timesheet_create", "Add Timesheet", "Record time against job/task.", "After completing work blocks.", ["Select job", "Enter time", "Add remarks", "Save"], ["Overlaps saved but flagged", "Closed jobs reject entries"], [], ["Log daily"], "Timesheet", "Create", "/timesheets/create"),
    _entry(31, "timesheet_edit", "Edit Timesheet", "Correct existing entry.", "When inaccurate data entered.", ["Open entry", "Edit allowed fields", "Save"], ["All edits audited"], [], ["Minimize retro edits"], "Timesheet", "Edit", "/timesheets/:id/edit"),
    _entry(32, "timesheet_overlap_report", "Timesheet Overlaps", "Overlap exception report.", "For manager exception handling.", ["Filter by employee/date", "Review conflicts"], ["Overlaps system-detected"], [], ["Resolve daily"], "Timesheet", "Overlap", "/timesheets/overlaps"),
    _entry(33, "timesheet_expense_section", "Expense Details", "Capture job-linked expenses.", "When reimbursable costs incurred.", ["Add expense line", "Enter amount", "Save"], ["Expense must belong to timesheet"], [], ["Attach proof where possible"], "Timesheet", "Expense", "/timesheets/:id/expenses"),
    _entry(34, "timesheet_reimbursement_section", "Reimbursement Details", "Record reimbursement claims.", "When employee claims reimbursement.", ["Add claim", "Enter details", "Save"], ["May require approval"], [], ["Keep reimbursement clearly separated"], "Timesheet", "Reimbursement", "/timesheets/:id/reimbursements"),
    _entry(35, "approval_inbox", "Approval Inbox", "Pending approval queue.", "Daily approval clearing.", ["Filter pending", "Open detail", "Review source", "Approve/reject"], ["Reject requires reason"], [], ["Start with SLA/high priority"], "Approval", "Inbox", "/approvals"),
    _entry(36, "approval_detail", "Approval Detail", "Review item before decision.", "Before approve/reject action.", ["Review summary", "Review source details", "Review trail", "Act"], ["L1 then L2 chain applies"], [], ["Use full detail before reject"], "Approval", "Detail", "/approvals/:id"),
    _entry(37, "approval_reject_modal", "Reject Approval", "Reject with mandatory reason.", "When item is not acceptable.", ["Enter reason", "Submit rejection"], ["Reason is mandatory"], ["Blank/whitespace reason"], ["Give actionable feedback"], "Approval", "RejectModal", "/approvals/:id/reject"),
    _entry(38, "approval_history", "Approval History", "Past approved/rejected/sent-back items.", "For compliance follow-up.", ["Filter history", "Open item"], ["History audit-backed"], [], ["Use to identify bottlenecks"], "Approval", "History", "/approvals/history"),
    _entry(39, "ticket_list", "Ticket List", "ERP-synced support tickets.", "To monitor support flow.", ["Filter status", "Open detail", "Add follow-up"], ["Ticket number from ERP"], [], ["Check open+customer tabs first"], "Ticket", "List", "/tickets"),
    _entry(40, "ticket_create", "Create Ticket", "Create project-less support ticket.", "For customer issues.", ["Enter customer and issue", "Set priority", "Assign", "Save"], ["Customer mandatory", "Project linkage optional"], [], ["Use clear issue narrative"], "Ticket", "Create", "/tickets/create"),
    _entry(41, "ticket_detail", "Ticket Detail", "Complete support record.", "Before updating follow-ups.", ["Open ticket", "Review issue+history"], ["SLA by priority"], [], ["Check customer context"], "Ticket", "Detail", "/tickets/:id"),
    _entry(42, "ticket_followup", "Ticket Follow-up", "Operational updates per ticket.", "After any customer update.", ["Select follow-up type", "Add remark", "Update status", "Save"], ["Follow-up appended to history"], [], ["Log each interaction"], "Ticket", "Followup", "/tickets/:id/followups"),
    _entry(43, "rbac_role_list", "Role List", "Manage system roles.", "When updating access structure.", ["Open roles", "Select/create role", "Open privileges"], ["Role changes impact access"], [], ["Keep role count minimal"], "RBAC", "RoleList", "/masters/rbac/roles"),
    _entry(44, "rbac_role_create", "Create Role", "Create a new role.", "When new access pattern needed.", ["Enter role name", "Save", "Configure privileges"], ["No duplicate role names"], [], ["Use function-based names"], "RBAC", "RoleCreate", "/masters/rbac/roles/create"),
    _entry(45, "rbac_privilege_tree", "Privilege Tree", "Assign module/field-level access.", "After role creation.", ["Expand module tree", "Select privileges", "Set scope", "Save"], ["Every feature maps to privilege"], [], ["Test with sample user"], "RBAC", "PrivilegeTree", "/masters/rbac/privileges"),
    _entry(46, "user_master_list", "User Master List", "View all users.", "For org/access maintenance.", ["Filter/search users", "Open user"], ["Sensitive fields may be masked"], [], ["Review reporting lines frequently"], "Masters", "Users", "/masters/users"),
    _entry(47, "user_master_create", "Create User", "Onboard a user with role/scope.", "When onboarding employees.", ["Enter identity", "Set manager", "Set approval toggle", "Set role+scope", "Save"], ["Email unique", "Role mandatory"], [], ["Set employee group correctly"], "Masters", "UsersCreate", "/masters/users/create"),
    _entry(48, "company_master_list", "Company Master", "Maintain company records.", "For multi-company config.", ["Review companies", "Add/edit"], ["GST and address validity required"], [], ["Keep branding updated"], "Masters", "Company", "/masters/company"),
    _entry(49, "branch_master_list", "Branch Master", "Maintain branches by company.", "When branch structure changes.", ["Select company", "Add/edit branch"], ["Branch belongs to company"], [], ["Use consistent location names"], "Masters", "Branch", "/masters/branch"),
    _entry(50, "department_master_list", "Department Master", "Maintain departments.", "For org updates.", ["Select company/branch", "Add/edit department"], ["Department must map to branch/company"], [], ["Link correct head user"], "Masters", "Department", "/masters/department"),
    _entry(51, "task_group_master", "Task Group Master", "Classify task master groups.", "Before expanding task master catalog.", ["Add group", "Save"], ["Task master belongs to group"], [], ["Use reusable broad groups"], "Masters", "TaskGroup", "/task-master/groups"),
    _entry(52, "task_master_list", "Task Master", "Maintain standard task definitions.", "Before task/job creation at scale.", ["Add task", "Assign group", "Set benchmark hours", "Save"], ["Task and job creation rely on this"], [], ["Review benchmarks periodically"], "Masters", "TaskMaster", "/task-master"),
    _entry(53, "interconnect_grid", "Interconnect Grid", "Module relationship map.", "To verify system flow design.", ["Open grid", "Review source/target", "Inspect missing flows"], ["Critical flows must be mapped"], [], ["Use during QA and debugging"], "Interconnect", "Grid", "/interconnect"),
    _entry(54, "interconnect_coverage_matrix", "Coverage Matrix", "Covered vs uncovered interconnects.", "During audits/UAT.", ["Open matrix", "Review gaps", "Resolve"], ["Uncovered flow indicates mismatch"], [], ["Run after each release"], "Interconnect", "Coverage", "/interconnect/coverage"),
    _entry(55, "report_templates", "Report Templates", "Manage reusable report structures.", "When recurring reports are needed.", ["Open template list", "Create/edit template", "Save fields"], ["Only visible fields allowed"], [], ["Create role-specific templates"], "Reports", "Templates", "/reports/templates"),
    _entry(56, "report_run", "Run Report", "Generate report output with filters.", "For operational/management reporting.", ["Select report", "Apply filters", "Toggle fields", "Preview", "Export"], ["At least one field required"], [], ["Save repeated formats"], "Reports", "Run", "/reports/run"),
    _entry(57, "report_export", "Export Report", "Download report output.", "After validation in preview.", ["Choose format", "Confirm export"], ["Export follows RBAC"], [], ["Excel for analysis, PDF for sharing"], "Reports", "Export", "/reports/export"),
    _entry(58, "report_schedules", "Scheduled Reports", "Automate periodic reporting.", "For recurring delivery.", ["Choose template", "Choose schedule", "Save"], ["Recipients must have access"], [], ["Use careful cadence"], "Reports", "Schedules", "/reports/schedules"),
    _entry(59, "analytics_prebuilt", "Prebuilt Analytics", "Standard charts for module insights.", "For quick visual review.", ["Apply filters", "Review charts", "Drill down"], ["Filters affect all charts"], [], ["Use trends for insight"], "Analytics", "Prebuilt", "/analytics/prebuilt"),
    _entry(60, "analytics_saved_views", "Saved Views", "Open saved analytical perspectives.", "For repeated analysis.", ["Open saved views", "Select view", "Review output"], ["Saved views are user-specific unless shared"], [], ["Use clear names"], "Analytics", "SavedViews", "/analytics/saved-views"),
    _entry(61, "analytics_alert_rules", "Alert Rules", "Threshold-driven analytics alerts.", "For exception monitoring.", ["Review rules", "Activate/deactivate"], ["Some alerts may be system-managed"], [], ["Use for SLA/delay alerts"], "Analytics", "AlertRules", "/analytics/alert-rules"),
    _entry(62, "chat_home", "Chat Home", "Recent DMs and channels.", "For coordinated communication.", ["Search/select chat", "Open conversation", "Send messages/files"], ["Visibility based on membership"], [], ["Prefer project channels for traceability"], "Chat", "Home", "/chat"),
    _entry(63, "chat_dm", "Direct Message", "1:1 chat between users.", "For direct coordination.", ["Open DM", "Send message", "Attach file if needed"], ["Messages are real-time"], [], ["Use contextual channels for decisions"], "Chat", "DM", "/chat/dm/:id"),
    _entry(64, "chat_channel", "Project Channel", "Group collaboration stream.", "For shared project communication.", ["Open channel", "Post updates", "Tag users"], ["Membership controls access"], [], ["Keep updates structured"], "Chat", "Channel", "/chat/channel/:id"),
    _entry(65, "notification_center", "Notification Center", "System alerts and updates.", "To act on approvals, mentions and SLA alerts.", ["Open notifications", "Filter", "Click to navigate"], ["Critical alerts are system-generated"], [], ["Handle high priority first"], "Notifications", "Center", "/notifications"),
    _entry(66, "notification_settings", "Notification Settings", "Manage alert preferences.", "When adjusting personal alert behavior.", ["Toggle settings", "Save"], ["Critical alerts may be non-disableable"], [], ["Keep approval+SLA alerts enabled"], "Notifications", "Settings", "/notifications/settings"),
    _entry(67, "audit_log_list", "Audit Log", "Immutable log of system actions.", "For compliance and investigation.", ["Filter logs", "Open entry", "Review changes"], ["Audit logs are immutable"], [], ["Use reference filter for quick trace"], "Audit", "List", "/audit/logs"),
    _entry(68, "audit_log_detail", "Audit Log Detail", "Field-level before/after record.", "When exact change must be verified.", ["Open audit entry", "Review changed fields and timestamp"], ["Shows old vs new values"], [], ["Use for delay/edit investigations"], "Audit", "Detail", "/audit/logs/:id"),
]
