METRIC_CATALOG = {
    # Counts
    "ticket_count": {"measure": "count", "entity": "ticket"},
    "task_count": {"measure": "count", "entity": "task"},
    "job_count": {"measure": "count", "entity": "job"},
    "completed_count": {"measure": "count", "entity": "job", "status_in": ["Completed", "Billed", "Closed"]},
    "pending_count": {"measure": "count", "entity": "job", "status_in": ["Draft", "Pending", "In Progress", "Critical"]},
    "overdue_count": {"measure": "count", "entity": "job", "overdue": True},
    "critical_count": {"measure": "count", "entity": "job", "critical": True},
    "reopened_count": {"measure": "count", "entity": "job", "status_in": ["Reopened"]},
    "billable_count": {"measure": "count", "entity": "job", "billable": True},
    "non_billable_count": {"measure": "count", "entity": "job", "billable": False},
    "billing_ready_count": {"measure": "count", "entity": "job", "billing_status_in": ["Ready to Bill"]},
    "billing_blocked_count": {"measure": "count", "entity": "job", "billing_status_in": ["Blocked"]},
    "approval_pending_count": {"measure": "count", "entity": "approval", "approval_status_in": ["Pending"]},
    "approval_rejected_count": {"measure": "count", "entity": "approval", "approval_status_in": ["Rejected"]},
    # Hours
    "total_expected_hours": {"measure": "sum", "entity": "job", "field": "expected_hours"},
    "total_actual_hours": {"measure": "sum", "entity": "job", "field": "actual_hours"},
    "billable_hours": {"measure": "sum", "entity": "timesheet", "field": "billable_hours"},
    "non_billable_hours": {"measure": "sum", "entity": "timesheet", "field": "non_billable_hours"},
    # Financial
    "total_labor_cost": {"measure": "sum", "entity": "job", "field": "labor_cost"},
    "total_expense_amount": {"measure": "sum", "entity": "timesheet", "field": "expense_total"},
    "total_reimbursement_amount": {"measure": "sum", "entity": "timesheet", "field": "reimbursement_total"},
    "total_overhead": {"measure": "sum", "entity": "job", "field": "overhead"},
    "total_cost_to_company": {"measure": "sum", "entity": "job", "field": "total_cost_to_company"},
    "total_billed_amount": {"measure": "sum", "entity": "job", "field": "billed_amount"},
    "total_recovery": {"measure": "sum", "entity": "job", "field": "billed_amount"},
    "total_profit": {"measure": "sum", "entity": "job", "field": "profit_positive"},
    "total_loss": {"measure": "sum", "entity": "job", "field": "loss_positive"},
    "margin_percent": {"measure": "ratio", "entity": "job", "numerator": "profit", "denominator": "billed_amount"},
    # Control
    "rollover_count": {"measure": "sum", "entity": "job", "field": "rollover_count"},
    "three_plus_rollover_count": {"measure": "count", "entity": "job", "rollover_gte": 3},
    "dependency_blockage_count": {"measure": "count", "entity": "job", "status_in": ["Blocked"]},
    "transfer_awaiting_acceptance_count": {"measure": "count", "entity": "job", "transfer_status_in": ["Awaiting Acceptance"]},
    "transfer_rejected_count": {"measure": "count", "entity": "job", "transfer_status_in": ["Rejected"]},
}

WIDGET_LIBRARY = {
    "summary_cards": [
        "job_count",
        "pending_count",
        "completed_count",
        "overdue_count",
        "critical_count",
        "billing_ready_count",
        "billing_blocked_count",
        "total_expected_hours",
        "total_actual_hours",
        "total_cost_to_company",
        "total_billed_amount",
        "margin_percent",
    ],
    "employee_widgets": [
        "job_count",
        "completed_count",
        "pending_count",
        "overdue_count",
        "billable_hours",
        "non_billable_hours",
        "total_labor_cost",
        "total_recovery",
        "rollover_count",
        "three_plus_rollover_count",
    ],
    "client_widgets": [
        "ticket_count",
        "task_count",
        "job_count",
        "billable_count",
        "non_billable_count",
        "total_actual_hours",
        "total_cost_to_company",
        "total_billed_amount",
        "total_profit",
        "total_loss",
    ],
}
