from datetime import datetime

from sqlalchemy import BIGINT, Boolean, Column, DateTime, Integer, String, Text

from app.database.session import Base


class WmTicket(Base):
    __tablename__ = "wm_ticket"

    ticket_id = Column(BIGINT, primary_key=True, autoincrement=True)
    ticket_no = Column(String(50), nullable=False, unique=True, index=True)
    customer_id = Column(BIGINT, nullable=True, index=True)
    external_ticket_no = Column(String(50), nullable=True, unique=True)
    customer_name = Column(String(150), nullable=True)
    product = Column(String(120), nullable=True)
    license_name_or_package = Column(String(150), nullable=True)
    remark = Column(Text, nullable=True)
    category = Column(String(80), nullable=True)
    ticket_type = Column(String(40), nullable=True)
    subject = Column(String(300), nullable=False)
    description = Column(Text, nullable=False)
    priority = Column(String(20), nullable=False, default="MEDIUM")
    status = Column(String(30), nullable=False, default="NEW")
    channel = Column(String(30), nullable=False, default="PORTAL")
    assign_executive_id = Column(BIGINT, nullable=True)
    assign_executive_name = Column(String(120), nullable=True)
    created_by = Column(BIGINT, nullable=False)
    company_id = Column(BIGINT, nullable=True)
    branch_id = Column(BIGINT, nullable=True)
    department_id = Column(BIGINT, nullable=True)
    mobile = Column(String(30), nullable=True)
    contact_person = Column(String(120), nullable=True)
    email = Column(String(200), nullable=True)
    address = Column(Text, nullable=True)
    pack_validity = Column(DateTime, nullable=True)
    sms_balance = Column(BIGINT, nullable=True)
    whatsapp_balance = Column(BIGINT, nullable=True)
    username = Column(String(120), nullable=True)
    max_user = Column(Integer, nullable=True)
    attachments = Column(Text, nullable=True)
    assigned_on = Column(DateTime, nullable=True)
    first_response_at = Column(DateTime, nullable=True)
    resolved_at = Column(DateTime, nullable=True)
    closed_at = Column(DateTime, nullable=True)
    reopened_at = Column(DateTime, nullable=True)
    reopen_count = Column(Integer, nullable=False, default=0)
    last_followup_at = Column(DateTime, nullable=True)
    last_followup_by = Column(BIGINT, nullable=True)
    escalation_level = Column(Integer, nullable=False, default=0)
    escalation_status = Column(String(30), nullable=False, default="NONE")
    response_sla_due_at = Column(DateTime, nullable=True)
    closure_sla_due_at = Column(DateTime, nullable=True)
    response_sla_status = Column(String(30), nullable=False, default="PENDING")
    closure_sla_status = Column(String(30), nullable=False, default="PENDING")
    response_delay_minutes = Column(BIGINT, nullable=False, default=0)
    closure_delay_minutes = Column(BIGINT, nullable=False, default=0)
    response_sla_paused = Column(Boolean, nullable=False, default=False)
    closure_sla_paused = Column(Boolean, nullable=False, default=False)
    total_pause_minutes = Column(BIGINT, nullable=False, default=0)
    is_critical = Column(Boolean, nullable=False, default=False)
    aging_minutes = Column(BIGINT, nullable=False, default=0)
    resolution_note = Column(Text, nullable=True)
    created_on = Column(DateTime, nullable=False, default=datetime.utcnow)
    created_at = Column(DateTime, nullable=False, default=datetime.utcnow)
    updated_on = Column(DateTime, nullable=True)
    updated_at = Column(DateTime, nullable=True)
    updated_by = Column(BIGINT, nullable=True)
