export const WORK_STATUSES = ['Backlog', 'In Progress', 'Blocked', 'Review', 'Done']
export const PRIORITY_LEVELS = ['Low', 'Medium', 'High', 'Critical']

export const seedWorkItems = [
  {
    id: 'TASK-1042',
    type: 'Task',
    title: 'Quarter-end payroll validation',
    status: 'In Progress',
    assignee: 'Aisha M',
    manager: 'Rohan P',
    client: 'Internal Finance',
    priority: 'High',
    dueDate: '2026-04-02',
    startDate: '2026-03-27',
    plannedHours: 14,
    actualHours: 9,
    freeCapacityHours: 3,
    dependency: 'JOB-8821',
    billable: false,
    rollover: 1,
    critical: true,
    section: 'Core Finance Ops',
    comments: ['Validated branch-level overtime flags', 'Awaiting one manager confirmation'],
  },
  {
    id: 'JOB-8821',
    type: 'Job',
    title: 'Employee variance reconciliation',
    status: 'Review',
    assignee: 'Vikas R',
    manager: 'Rohan P',
    client: 'Client Delta',
    priority: 'Medium',
    dueDate: '2026-03-31',
    startDate: '2026-03-25',
    plannedHours: 10,
    actualHours: 11,
    freeCapacityHours: 0,
    dependency: '-',
    billable: true,
    rollover: 0,
    critical: false,
    section: 'Client Delivery',
    comments: ['Variance delta narrowed to <2%', 'Ready for final QA sign-off'],
  },
  {
    id: 'TASK-1063',
    type: 'Task',
    title: 'Approval matrix refresh for branch transfers',
    status: 'Blocked',
    assignee: 'Nina S',
    manager: 'Arjun K',
    client: 'Internal Governance',
    priority: 'Critical',
    dueDate: '2026-03-29',
    startDate: '2026-03-21',
    plannedHours: 12,
    actualHours: 6,
    freeCapacityHours: 0,
    dependency: 'TASK-0988',
    billable: false,
    rollover: 2,
    critical: true,
    section: 'Governance Controls',
    comments: ['Waiting dependency acceptance from security team'],
  },
  {
    id: 'JOB-8904',
    type: 'Job',
    title: 'SLA breach root-cause packet',
    status: 'Backlog',
    assignee: 'Meera L',
    manager: 'Arjun K',
    client: 'Client Nova',
    priority: 'High',
    dueDate: '2026-04-05',
    startDate: '2026-03-30',
    plannedHours: 8,
    actualHours: 0,
    freeCapacityHours: 5,
    dependency: '-',
    billable: true,
    rollover: 0,
    critical: false,
    section: 'Client Delivery',
    comments: [],
  },
]
