global:
  scrape_interval: 15s
scrape_configs:
  - job_name: backend
    static_configs:
      - targets: ['backend-api:8000']
  - job_name: websocket
    static_configs:
      - targets: ['websocket-service:8010']
